Feature/sms check
wecode-bootcamp-korea/14-2nd-SUWEE-backend pull request #3
Opened 2020-12-02 09:17 UTC by jinybear

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 문자인증 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- User app의 model/view에 문자인증 로직 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 문자인증 구현 후 REST 통신을 시도하면 auth 관련 error 가 발생하여 django.auth 를 활성화 해놓은 상태입니다. 혹시 왜 이런건지 궁금합니다 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [0] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [0] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [0] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [0] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-02 11:06 UTC, soheon-lee commented on user/models.py
> +    auth_number = models.IntegerField(verbose_name='인증 번호')
코드 간격 정렬해주세요

2020-12-02 11:06 UTC, soheon-lee commented on user/views.py
> +            return Response({'message': 'OK'})
`status code` 명확히 기재해주시는 것이 좋을 것 같습니다. 꼭 메세지가 필요한 상황이 아니라면 메세지 바디 없이 status=200만 보내시는 것도 하나의 방법입니다.

2020-12-02 11:06 UTC, soheon-lee commented on user/views.py
> +            return Response({'message': 'Bad Request'}, status=400)
KeyError가 발생했을 때에는 Response도 KeyError를 정확히 알려주시는 것이 좋습니다.
그래야 어떤 에러인지 알고 다시 정상적인 요청을 보낼 수 있기 때문입니다 :)

2020-12-02 11:38 UTC, jinybear commented on user/models.py
> +    auth_number = models.IntegerField(verbose_name='인증 번호')
넵

2020-12-02 11:39 UTC, jinybear commented on user/views.py
> +            return Response({'message': 'OK'})
넵 반영하겠습니다

2020-12-02 11:40 UTC, jinybear commented on user/views.py
> +            return Response({'message': 'Bad Request'}, status=400)
네 KEY_ERROR 로 메시지 바꾸고 SUCCESS 상황시 status 추가하겠습니다

2020-12-03 06:19 UTC, lordmyshepherd requested changes

2020-12-03 06:19 UTC, lordmyshepherd commented on user/views.py
> +class SMSCheckView(APIView):
View의 sublclass인 `APIView`는 `View` 어떤 기능이 다른가요??

2020-12-03 06:19 UTC, lordmyshepherd commented on user/views.py
> +            return Response({'message': 'SUCCESS'}, status=201)
`from rest_framework import status` rest_framework 에서 status를 import해서 사용하실 경우에 
status 코드를 직접 '201'로 넣어주는 것이 아니라 status 객체 속성에 HTTP status code를 찾아서 전달해주세요!

2020-12-03 06:19 UTC, lordmyshepherd commented on user/views.py
> +
serializer를 사용하지 않으신 이유가 있으신가요??

2020-12-03 06:19 UTC, lordmyshepherd commented on user/views.py
> +        try:
마찬가지로 serializer를 사용하지 않는 이유가 있으신가요??

2020-12-03 06:19 UTC, lordmyshepherd commented on suwee/urls.py
> +        path('user', include('user.urls'))
rest_framework에서 router를 import해서 url을 작성해주세요!

2020-12-03 10:49 UTC, jinybear commented on suwee/urls.py
> +        path('user', include('user.urls'))
DRF 에 대한 이해도가 부족한 상태에서 기능을 사용한 상황이라 DRF 대신 기본 View 방식으로 변경하였습니다.
다만 기능이 궁금하여 가볍게 분석을 해본결과를 정리합니다.
1. model 정보를 requester에게 제공할 때 serializer를 통해 제공할 field를 정의, 매번 json 형식으로 짜 맞추지 않고 serializer로 
    response data를 만들 수 있다.
2. data를 제공하기 위해 응답메시지를 가공하는 과정에서 status 를 일일이 기재하는 대신 함수를 사용할 수 있다.
   (ex. get_object_or_404)
3. request, response 과정에서 request가 보내는 데이터(param, body...)를 좀더 쉽게 parsing 할 수 있고 response도 http, json 
   전용 response가 아닌 DRF에서 제공하는 response 하나로 처리 가능하다.

그 외 더 많은 기능이 있을것인데 지금은 공부해서 적용할 단계는 아닌듯 하여 이렇게 글을 남김니다.

2020-12-04 05:21 UTC, lordmyshepherd commented on suwee/urls.py
> +        path('user', include('user.urls'))
승진님! DRF 공식문서를 보는 것을 추천드립니다.
https://www.django-rest-framework.org/api-guide/status-codes/#status-codes

1. 이해하신게 맞습니다. 추가로 설명을 드리면, DRF의 serializer(직렬화)는 Django의 Form과 같은 개념이라고 생각하시면 되요. 
    Serializer의 역할은 크게 두가지가 있습니다.
    (1) serialization : model instance와 같은 데이터를 JSON과 같은 content type으로 쉽게 렌디랑 할 수 있는 python data type으로 변환 
    (2) deserialization : 들오는 데이터의 유효성을 검사 한 후 데이터를 다시 인스턴스와 같은 복잡한 데이터로 변환할 수 있습니다.

2. DRF는 status 코드도 정의가 되어 있습니다.
```
    from rest_framework import status
    status.HTTP_404_NOT_FOUND와 같은..
```

3. 네 맞습니다.

2020-12-04 05:22 UTC, lordmyshepherd commented on suwee/urls.py
> +        path('user', include('user.urls'))
DRF를 사용하신다면, APIView 또는 ViewSet을 사용해서 엔드포인트를 구현해주세요!

2020-12-04 05:22 UTC, lordmyshepherd commented on suwee/urls.py
> +        path('user', include('user.urls'))
Serializer도 사용해주세요!

2020-12-04 06:00 UTC, jinybear commented
conflict 조치 했습니다

2020-12-07 03:36 UTC, jinybear commented
병합 충돌 해결하여 다시 올립니다

2020-12-07 06:22 UTC, soheon-lee commented
LGTM

2020-12-07 06:22 UTC, soheon-lee commented
👍

2020-12-07 06:22 UTC, merged